insert into neighborhood (neighborhood_id, name, city, state) values (1, 'Flowdesk', 'Louisville', 'KY');
insert into neighborhood (neighborhood_id, name, city, state) values (2, 'Tresom', 'Norfolk', 'VA');
insert into neighborhood (neighborhood_id, name, city, state) values (3, 'Cookley', 'Waterbury', 'CT');
insert into neighborhood (neighborhood_id, name, city, state) values (4, 'Ronstring', 'Atlanta', 'GA');
insert into neighborhood (neighborhood_id, name, city, state) values (5, 'Aerified', 'Erie', 'PA');
insert into neighborhood (neighborhood_id, name, city, state) values (6, 'Pannier', 'Chicago', 'IL');
insert into neighborhood (neighborhood_id, name, city, state) values (7, 'Voyatouch', 'Sacramento', 'CA');
insert into neighborhood (neighborhood_id, name, city, state) values (8, 'Opela', 'New York City', 'NY');
insert into neighborhood (neighborhood_id, name, city, state) values (9, 'Duobam', 'San Diego', 'CA');
insert into neighborhood (neighborhood_id, name, city, state) values (10, 'Viva', 'Harrisburg', 'PA');
insert into neighborhood (neighborhood_id, name, city, state) values (11, 'Bitchip', 'Sioux City', 'IA');
insert into neighborhood (neighborhood_id, name, city, state) values (12, 'Cookley', 'Littleton', 'CO');
insert into neighborhood (neighborhood_id, name, city, state) values (13, 'Konklab', 'Houston', 'TX');
insert into neighborhood (neighborhood_id, name, city, state) values (14, 'Daltfresh', 'Birmingham', 'AL');
insert into neighborhood (neighborhood_id, name, city, state) values (15, 'Bytecard', 'Sacramento', 'CA');
insert into neighborhood (neighborhood_id, name, city, state) values (16, 'Gembucket', 'Orlando', 'FL');
insert into neighborhood (neighborhood_id, name, city, state) values (17, 'Y-find', 'Reno', 'NV');
insert into neighborhood (neighborhood_id, name, city, state) values (18, 'Mat Lam Tam', 'Saint Petersburg', 'FL');
insert into neighborhood (neighborhood_id, name, city, state) values (19, 'Andalax', 'Fort Lauderdale', 'FL');
insert into neighborhood (neighborhood_id, name, city, state) values (20, 'Kanlam', 'Reston', 'VA');
insert into neighborhood (neighborhood_id, name, city, state) values (21, 'Toughjoyfax', 'Brooklyn', 'NY');
insert into neighborhood (neighborhood_id, name, city, state) values (22, 'Tempsoft', 'Washington', 'DC');
insert into neighborhood (neighborhood_id, name, city, state) values (23, 'Latlux', 'Littleton', 'CO');
insert into neighborhood (neighborhood_id, name, city, state) values (24, 'Asoka', 'Newark', 'DE');
insert into neighborhood (neighborhood_id, name, city, state) values (25, 'Stronghold', 'Fort Wayne', 'IN');
insert into neighborhood (neighborhood_id, name, city, state) values (26, 'Fixflex', 'Roanoke', 'VA');
insert into neighborhood (neighborhood_id, name, city, state) values (27, 'Treeflex', 'Lexington', 'KY');
insert into neighborhood (neighborhood_id, name, city, state) values (28, 'Alpha', 'Bradenton', 'FL');
insert into neighborhood (neighborhood_id, name, city, state) values (30, 'Trippledex', 'Richmond', 'VA');
insert into neighborhood (neighborhood_id, name, city, state) values (31, 'Tin', 'Tulsa', 'OK');
insert into neighborhood (neighborhood_id, name, city, state) values (32, 'Bitwolf', 'Omaha', 'NE');
insert into neighborhood (neighborhood_id, name, city, state) values (33, 'Ronstring', 'Inglewood', 'CA');
insert into neighborhood (neighborhood_id, name, city, state) values (34, 'Transcof', 'Newark', 'NJ');
insert into neighborhood (neighborhood_id, name, city, state) values (35, 'Zaam-Dox', 'Simi Valley', 'CA');
insert into neighborhood (neighborhood_id, name, city, state) values (36, 'Trippledex', 'Austin', 'TX');
insert into neighborhood (neighborhood_id, name, city, state) values (37, 'Opela', 'Tuscaloosa', 'AL');
insert into neighborhood (neighborhood_id, name, city, state) values (38, 'Asoka', 'Dallas', 'TX');
insert into neighborhood (neighborhood_id, name, city, state) values (39, 'Bitwolf', 'Sacramento', 'CA');
insert into neighborhood (neighborhood_id, name, city, state) values (40, 'Regrant', 'Louisville', 'KY');
insert into neighborhood (neighborhood_id, name, city, state) values (41, 'Cookley', 'Washington', 'DC');
insert into neighborhood (neighborhood_id, name, city, state) values (42, 'Ventosanzap', 'Arlington', 'VA');
insert into neighborhood (neighborhood_id, name, city, state) values (43, 'Alphazap', 'Huntsville', 'AL');
insert into neighborhood (neighborhood_id, name, city, state) values (44, 'Sonsing', 'Fort Lauderdale', 'FL');
insert into neighborhood (neighborhood_id, name, city, state) values (45, 'Voyatouch', 'Green Bay', 'WI');
insert into neighborhood (neighborhood_id, name, city, state) values (46, 'Fintone', 'Abilene', 'TX');
insert into neighborhood (neighborhood_id, name, city, state) values (47, 'Andalax', 'Bethesda', 'MD');
insert into neighborhood (neighborhood_id, name, city, state) values (48, 'Greenlam', 'Chicago', 'IL');
insert into neighborhood (neighborhood_id, name, city, state) values (49, 'Flowdesk', 'Rochester', 'MN');
insert into neighborhood (neighborhood_id, name, city, state) values (50, 'Sub-Ex', 'Bakersfield', 'CA');
insert into neighborhood (neighborhood_id, name, city, state) values (51, 'It', 'Pompano Beach', 'FL');
insert into neighborhood (neighborhood_id, name, city, state) values (52, 'Stronghold', 'Nashville', 'TN');
insert into neighborhood (neighborhood_id, name, city, state) values (53, 'Toughjoyfax', 'Birmingham', 'AL');
insert into neighborhood (neighborhood_id, name, city, state) values (54, 'Job', 'Saint Petersburg', 'FL');
insert into neighborhood (neighborhood_id, name, city, state) values (55, 'Bytecard', 'Cincinnati', 'OH');
insert into neighborhood (neighborhood_id, name, city, state) values (56, 'Regrant', 'Saint Paul', 'MN');
insert into neighborhood (neighborhood_id, name, city, state) values (57, 'Cardguard', 'Marietta', 'GA');
insert into neighborhood (neighborhood_id, name, city, state) values (58, 'Sub-Ex', 'Tampa', 'FL');
insert into neighborhood (neighborhood_id, name, city, state) values (59, 'Y-find', 'Kalamazoo', 'MI');
insert into neighborhood (neighborhood_id, name, city, state) values (60, 'Fixflex', 'North Little Rock', 'AR');
insert into neighborhood (neighborhood_id, name, city, state) values (61, 'Aerified', 'Atlanta', 'GA');
insert into neighborhood (neighborhood_id, name, city, state) values (62, 'Tresom', 'Corpus Christi', 'TX');
insert into neighborhood (neighborhood_id, name, city, state) values (63, 'Y-Solowarm', 'Tampa', 'FL');
insert into neighborhood (neighborhood_id, name, city, state) values (64, 'Vagram', 'Sioux City', 'IA');
insert into neighborhood (neighborhood_id, name, city, state) values (65, 'Bitchip', 'Trenton', 'NJ');
insert into neighborhood (neighborhood_id, name, city, state) values (66, 'Wrapsafe', 'Charleston', 'WV');
insert into neighborhood (neighborhood_id, name, city, state) values (67, 'Hatity', 'Modesto', 'CA');
insert into neighborhood (neighborhood_id, name, city, state) values (68, 'Regrant', 'Grand Rapids', 'MI');
insert into neighborhood (neighborhood_id, name, city, state) values (69, 'Veribet', 'Colorado Springs', 'CO');
insert into neighborhood (neighborhood_id, name, city, state) values (70, 'Veribet', 'Hampton', 'VA');
insert into neighborhood (neighborhood_id, name, city, state) values (71, 'Veribet', 'New York City', 'NY');
insert into neighborhood (neighborhood_id, name, city, state) values (72, 'Holdlamis', 'Minneapolis', 'MN');
insert into neighborhood (neighborhood_id, name, city, state) values (73, 'Temp', 'Pasadena', 'CA');
insert into neighborhood (neighborhood_id, name, city, state) values (74, 'Temp', 'Louisville', 'KY');
insert into neighborhood (neighborhood_id, name, city, state) values (75, 'Greenlam', 'Winston Salem', 'NC');
insert into neighborhood (neighborhood_id, name, city, state) values (76, 'Otcom', 'Oklahoma City', 'OK');
insert into neighborhood (neighborhood_id, name, city, state) values (77, 'Bitwolf', 'Norfolk', 'VA');
insert into neighborhood (neighborhood_id, name, city, state) values (78, 'Pannier', 'Dallas', 'TX');
insert into neighborhood (neighborhood_id, name, city, state) values (79, 'Zoolab', 'Jeffersonville', 'IN');
insert into neighborhood (neighborhood_id, name, city, state) values (80, 'Zathin', 'Manassas', 'VA');
insert into neighborhood (neighborhood_id, name, city, state) values (81, 'Cardguard', 'Sioux Falls', 'SD');
insert into neighborhood (neighborhood_id, name, city, state) values (82, 'Job', 'Phoenix', 'AZ');
insert into neighborhood (neighborhood_id, name, city, state) values (83, 'Voyatouch', 'Saint Paul', 'MN');
insert into neighborhood (neighborhood_id, name, city, state) values (84, 'Cookley', 'Philadelphia', 'PA');
insert into neighborhood (neighborhood_id, name, city, state) values (85, 'Solarbreeze', 'Albuquerque', 'NM');
insert into neighborhood (neighborhood_id, name, city, state) values (86, 'Namfix', 'Akron', 'OH');
insert into neighborhood (neighborhood_id, name, city, state) values (87, 'Tempsoft', 'Charlotte', 'NC');
insert into neighborhood (neighborhood_id, name, city, state) values (88, 'Greenlam', 'Akron', 'OH');
insert into neighborhood (neighborhood_id, name, city, state) values (89, 'Ventosanzap', 'Daytona Beach', 'FL');
insert into neighborhood (neighborhood_id, name, city, state) values (90, 'Greenlam', 'Orlando', 'FL');
insert into neighborhood (neighborhood_id, name, city, state) values (91, 'Solarbreeze', 'Suffolk', 'VA');
insert into neighborhood (neighborhood_id, name, city, state) values (92, 'Temp', 'Corona', 'CA');
insert into neighborhood (neighborhood_id, name, city, state) values (93, 'Tresom', 'Washington', 'DC');
insert into neighborhood (neighborhood_id, name, city, state) values (94, 'Namfix', 'Colorado Springs', 'CO');
insert into neighborhood (neighborhood_id, name, city, state) values (95, 'Otcom', 'Milwaukee', 'WI');
insert into neighborhood (neighborhood_id, name, city, state) values (96, 'Quo Lux', 'Fresno', 'CA');
insert into neighborhood (neighborhood_id, name, city, state) values (97, 'Solarbreeze', 'Richmond', 'VA');
insert into neighborhood (neighborhood_id, name, city, state) values (98, 'Tin', 'Columbia', 'SC');
insert into neighborhood (neighborhood_id, name, city, state) values (99, 'Latlux', 'Des Moines', 'IA');
insert into neighborhood (neighborhood_id, name, city, state) values (100, 'Lotstring', 'Huntsville', 'TX');
insert into neighborhood (neighborhood_id, name, city, state) values (101, 'Subin', 'Greeley', 'CO');
insert into neighborhood (neighborhood_id, name, city, state) values (102, 'Asoka', 'Glendale', 'AZ');
insert into neighborhood (neighborhood_id, name, city, state) values (103, 'Rank', 'Manassas', 'VA');
insert into neighborhood (neighborhood_id, name, city, state) values (104, 'Matsoft', 'Oklahoma City', 'OK');
insert into neighborhood (neighborhood_id, name, city, state) values (105, 'Fintone', 'Anchorage', 'AK');
insert into neighborhood (neighborhood_id, name, city, state) values (106, 'Flowdesk', 'Washington', 'DC');
insert into neighborhood (neighborhood_id, name, city, state) values (107, 'Flexidy', 'Annapolis', 'MD');
insert into neighborhood (neighborhood_id, name, city, state) values (108, 'Fintone', 'Pittsburgh', 'PA');
insert into neighborhood (neighborhood_id, name, city, state) values (109, 'Bamity', 'Salem', 'OR');
insert into neighborhood (neighborhood_id, name, city, state) values (110, 'Y-find', 'Warren', 'OH');
insert into neighborhood (neighborhood_id, name, city, state) values (111, 'Bitwolf', 'Tampa', 'FL');
insert into neighborhood (neighborhood_id, name, city, state) values (112, 'Solarbreeze', 'Whittier', 'CA');
insert into neighborhood (neighborhood_id, name, city, state) values (113, 'Pannier', 'Madison', 'WI');
insert into neighborhood (neighborhood_id, name, city, state) values (114, 'Konklux', 'Washington', 'DC');
insert into neighborhood (neighborhood_id, name, city, state) values (115, 'Konklab', 'Oklahoma City', 'OK');
insert into neighborhood (neighborhood_id, name, city, state) values (116, 'Aerified', 'Montgomery', 'AL');
insert into neighborhood (neighborhood_id, name, city, state) values (117, 'Otcom', 'Sioux City', 'IA');
insert into neighborhood (neighborhood_id, name, city, state) values (118, 'Sonair', 'Charlotte', 'NC');
insert into neighborhood (neighborhood_id, name, city, state) values (119, 'Duobam', 'Durham', 'NC');
insert into neighborhood (neighborhood_id, name, city, state) values (120, 'Solarbreeze', 'Savannah', 'GA');
insert into neighborhood (neighborhood_id, name, city, state) values (121, 'Y-find', 'Boise', 'ID');
insert into neighborhood (neighborhood_id, name, city, state) values (122, 'Zamit', 'Washington', 'DC');
insert into neighborhood (neighborhood_id, name, city, state) values (123, 'Transcof', 'South Bend', 'IN');
insert into neighborhood (neighborhood_id, name, city, state) values (124, 'Wrapsafe', 'Greenville', 'SC');
insert into neighborhood (neighborhood_id, name, city, state) values (125, 'Vagram', 'Washington', 'DC');
insert into neighborhood (neighborhood_id, name, city, state) values (126, 'Otcom', 'Amarillo', 'TX');
insert into neighborhood (neighborhood_id, name, city, state) values (127, 'Voyatouch', 'Syracuse', 'NY');
insert into neighborhood (neighborhood_id, name, city, state) values (128, 'Sonsing', 'Atlanta', 'GA');
insert into neighborhood (neighborhood_id, name, city, state) values (129, 'Tin', 'Dallas', 'TX');
insert into neighborhood (neighborhood_id, name, city, state) values (130, 'Tin', 'Atlanta', 'GA');
insert into neighborhood (neighborhood_id, name, city, state) values (131, 'Job', 'Springfield', 'IL');
insert into neighborhood (neighborhood_id, name, city, state) values (132, 'Ronstring', 'Augusta', 'GA');
insert into neighborhood (neighborhood_id, name, city, state) values (133, 'Veribet', 'Washington', 'DC');
insert into neighborhood (neighborhood_id, name, city, state) values (134, 'Cookley', 'Saint Cloud', 'MN');
insert into neighborhood (neighborhood_id, name, city, state) values (135, 'Otcom', 'New Orleans', 'LA');
insert into neighborhood (neighborhood_id, name, city, state) values (136, 'Zamit', 'Salt Lake City', 'UT');
insert into neighborhood (neighborhood_id, name, city, state) values (137, 'Cardguard', 'Fullerton', 'CA');
insert into neighborhood (neighborhood_id, name, city, state) values (138, 'Cookley', 'Tallahassee', 'FL');
insert into neighborhood (neighborhood_id, name, city, state) values (139, 'Sonair', 'New York City', 'NY');
insert into neighborhood (neighborhood_id, name, city, state) values (140, 'Stim', 'Minneapolis', 'MN');
insert into neighborhood (neighborhood_id, name, city, state) values (141, 'Y-Solowarm', 'Lansing', 'MI');
insert into neighborhood (neighborhood_id, name, city, state) values (142, 'Toughjoyfax', 'Houston', 'TX');
insert into neighborhood (neighborhood_id, name, city, state) values (143, 'Voyatouch', 'Boulder', 'CO');
insert into neighborhood (neighborhood_id, name, city, state) values (144, 'Tres-Zap', 'Chicago', 'IL');
insert into neighborhood (neighborhood_id, name, city, state) values (145, 'Sub-Ex', 'Baton Rouge', 'LA');
insert into neighborhood (neighborhood_id, name, city, state) values (146, 'Matsoft', 'Seattle', 'WA');
insert into neighborhood (neighborhood_id, name, city, state) values (147, 'Aerified', 'New Orleans', 'LA');
insert into neighborhood (neighborhood_id, name, city, state) values (148, 'Temp', 'Washington', 'DC');
insert into neighborhood (neighborhood_id, name, city, state) values (149, 'Home Ing', 'Warren', 'MI');
insert into neighborhood (neighborhood_id, name, city, state) values (150, 'Bitchip', 'Manchester', 'NH');
insert into neighborhood (neighborhood_id, name, city, state) values (151, 'Gembucket', 'Philadelphia', 'PA');
insert into neighborhood (neighborhood_id, name, city, state) values (152, 'It', 'Charlotte', 'NC');
insert into neighborhood (neighborhood_id, name, city, state) values (153, 'Biodex', 'Washington', 'DC');
insert into neighborhood (neighborhood_id, name, city, state) values (154, 'Lotlux', 'Gary', 'IN');
insert into neighborhood (neighborhood_id, name, city, state) values (155, 'Regrant', 'New Haven', 'CT');
insert into neighborhood (neighborhood_id, name, city, state) values (156, 'Viva', 'Chicago', 'IL');
insert into neighborhood (neighborhood_id, name, city, state) values (157, 'Aerified', 'San Diego', 'CA');
insert into neighborhood (neighborhood_id, name, city, state) values (158, 'Keylex', 'Beaumont', 'TX');
insert into neighborhood (neighborhood_id, name, city, state) values (159, 'Overhold', 'Austin', 'TX');
insert into neighborhood (neighborhood_id, name, city, state) values (160, 'Temp', 'Portland', 'OR');
insert into neighborhood (neighborhood_id, name, city, state) values (161, 'Solarbreeze', 'Salt Lake City', 'UT');
insert into neighborhood (neighborhood_id, name, city, state) values (162, 'Rank', 'Berkeley', 'CA');
insert into neighborhood (neighborhood_id, name, city, state) values (163, 'Y-find', 'Austin', 'TX');
insert into neighborhood (neighborhood_id, name, city, state) values (164, 'Fintone', 'Stockton', 'CA');
insert into neighborhood (neighborhood_id, name, city, state) values (165, 'Zontrax', 'Bradenton', 'FL');
insert into neighborhood (neighborhood_id, name, city, state) values (166, 'Y-Solowarm', 'Chattanooga', 'TN');
insert into neighborhood (neighborhood_id, name, city, state) values (167, 'Rank', 'Reno', 'NV');
insert into neighborhood (neighborhood_id, name, city, state) values (168, 'Flexidy', 'Kansas City', 'KS');
insert into neighborhood (neighborhood_id, name, city, state) values (169, 'Tresom', 'New York City', 'NY');
insert into neighborhood (neighborhood_id, name, city, state) values (170, 'Zaam-Dox', 'Scranton', 'PA');
insert into neighborhood (neighborhood_id, name, city, state) values (171, 'Duobam', 'Rochester', 'NY');
insert into neighborhood (neighborhood_id, name, city, state) values (172, 'Sub-Ex', 'Everett', 'WA');
insert into neighborhood (neighborhood_id, name, city, state) values (173, 'Keylex', 'Newark', 'NJ');
insert into neighborhood (neighborhood_id, name, city, state) values (174, 'Zoolab', 'Fort Worth', 'TX');
insert into neighborhood (neighborhood_id, name, city, state) values (175, 'Holdlamis', 'Tacoma', 'WA');
insert into neighborhood (neighborhood_id, name, city, state) values (176, 'Quo Lux', 'Charleston', 'WV');
insert into neighborhood (neighborhood_id, name, city, state) values (177, 'Zoolab', 'Chicago', 'IL');
insert into neighborhood (neighborhood_id, name, city, state) values (178, 'Regrant', 'Kissimmee', 'FL');
insert into neighborhood (neighborhood_id, name, city, state) values (179, 'Pannier', 'Lubbock', 'TX');
insert into neighborhood (neighborhood_id, name, city, state) values (180, 'Solarbreeze', 'Washington', 'DC');
insert into neighborhood (neighborhood_id, name, city, state) values (181, 'Flexidy', 'San Angelo', 'TX');
insert into neighborhood (neighborhood_id, name, city, state) values (182, 'Toughjoyfax', 'Lexington', 'KY');
insert into neighborhood (neighborhood_id, name, city, state) values (183, 'Sonair', 'Portland', 'OR');
insert into neighborhood (neighborhood_id, name, city, state) values (184, 'Opela', 'Rochester', 'NY');
insert into neighborhood (neighborhood_id, name, city, state) values (185, 'Biodex', 'Fort Collins', 'CO');
insert into neighborhood (neighborhood_id, name, city, state) values (186, 'Latlux', 'Roanoke', 'VA');
insert into neighborhood (neighborhood_id, name, city, state) values (187, 'Prodder', 'Erie', 'PA');
insert into neighborhood (neighborhood_id, name, city, state) values (188, 'Lotlux', 'Lincoln', 'NE');
insert into neighborhood (neighborhood_id, name, city, state) values (189, 'Rank', 'Mobile', 'AL');
insert into neighborhood (neighborhood_id, name, city, state) values (190, 'Andalax', 'Oklahoma City', 'OK');
insert into neighborhood (neighborhood_id, name, city, state) values (191, 'Opela', 'Nashville', 'TN');
insert into neighborhood (neighborhood_id, name, city, state) values (192, 'Tempsoft', 'Gulfport', 'MS');
insert into neighborhood (neighborhood_id, name, city, state) values (193, 'Tresom', 'Houston', 'TX');
insert into neighborhood (neighborhood_id, name, city, state) values (194, 'Otcom', 'Saint Paul', 'MN');
insert into neighborhood (neighborhood_id, name, city, state) values (195, 'Latlux', 'Tacoma', 'WA');
insert into neighborhood (neighborhood_id, name, city, state) values (196, 'Bytecard', 'Winston Salem', 'NC');
insert into neighborhood (neighborhood_id, name, city, state) values (197, 'Voyatouch', 'Arvada', 'CO');
insert into neighborhood (neighborhood_id, name, city, state) values (198, 'Fix San', 'Phoenix', 'AZ');
insert into neighborhood (neighborhood_id, name, city, state) values (199, 'Zamit', 'Lexington', 'KY');
insert into neighborhood (neighborhood_id, name, city, state) values (200, 'Subin', 'Portland', 'OR');
